/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'completedTournamentsCount' : bigint,
  'activeTournamentsCount' : bigint,
  'recentTransactions' : Array<Transaction>,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'totalCommissionEarned' : bigint,
}
export type MatchType = { 'duo' : null } |
  { 'solo' : null } |
  { 'squad' : null };
export interface Notification {
  'notificationType' : NotificationType,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export type NotificationType = { 'result' : null } |
  { 'matchReminder' : null } |
  { 'walletUpdate' : null };
export interface Result {
  'userId' : Principal,
  'totalPoints' : bigint,
  'position' : bigint,
  'tournamentId' : bigint,
  'kills' : bigint,
}
export interface RevenueReport {
  'totalCommissionProfit' : bigint,
  'totalPrizesDistributed' : bigint,
  'totalEntryFeesCollected' : bigint,
}
export interface RoomCredentials { 'roomPassword' : string, 'roomId' : string }
export interface Tournament {
  'matchType' : MatchType,
  'status' : TournamentStatus,
  'title' : string,
  'participants' : Array<Principal>,
  'mapType' : string,
  'roomPassword' : [] | [string],
  'totalSlots' : bigint,
  'entryFee' : bigint,
  'currentSlots' : bigint,
  'roomId' : [] | [string],
  'dateTime' : bigint,
  'prizePool' : bigint,
}
export type TournamentStatus = { 'active' : null } |
  { 'upcoming' : null } |
  { 'cancelled' : null } |
  { 'completed' : null };
export interface Transaction {
  'transactionType' : TransactionType,
  'description' : string,
  'timestamp' : bigint,
  'amount' : bigint,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile {
  'freeFireUID' : string,
  'referralCode' : string,
  'username' : string,
  'totalWins' : bigint,
  'email' : string,
  'referredBy' : [] | [string],
  'isBanned' : boolean,
  'phoneNumber' : string,
  'walletBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFunds' : ActorMethod<[bigint], undefined>,
  'adjustWallet' : ActorMethod<[Principal, bigint, boolean, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[Principal], undefined>,
  'createTournament' : ActorMethod<
    [string, MatchType, bigint, bigint, string, bigint, bigint],
    bigint
  >,
  'deleteTournament' : ActorMethod<[bigint], undefined>,
  'editTournament' : ActorMethod<
    [bigint, string, MatchType, bigint, bigint, string, bigint, bigint],
    undefined
  >,
  'getAllTournaments' : ActorMethod<[], Array<[bigint, Tournament]>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getResults' : ActorMethod<[bigint], Array<Result>>,
  'getRevenueReport' : ActorMethod<[], RevenueReport>,
  'getRoomCredentials' : ActorMethod<[bigint], [] | [RoomCredentials]>,
  'getTournament' : ActorMethod<[bigint], [] | [Tournament]>,
  'getTournamentParticipants' : ActorMethod<[bigint], Array<Principal>>,
  'getTransactionHistory' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinTournament' : ActorMethod<[bigint], undefined>,
  'leaveTournament' : ActorMethod<[bigint], undefined>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'register' : ActorMethod<
    [string, string, string, string, [] | [string]],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unbanUser' : ActorMethod<[Principal], undefined>,
  'uploadResults' : ActorMethod<
    [bigint, Array<[Principal, bigint, bigint]>],
    undefined
  >,
  'uploadRoomCredentials' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];