/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchType = IDL.Variant({
  'duo' : IDL.Null,
  'solo' : IDL.Null,
  'squad' : IDL.Null,
});
export const TournamentStatus = IDL.Variant({
  'active' : IDL.Null,
  'upcoming' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
});
export const Tournament = IDL.Record({
  'matchType' : MatchType,
  'status' : TournamentStatus,
  'title' : IDL.Text,
  'participants' : IDL.Vec(IDL.Principal),
  'mapType' : IDL.Text,
  'roomPassword' : IDL.Opt(IDL.Text),
  'totalSlots' : IDL.Nat,
  'entryFee' : IDL.Nat,
  'currentSlots' : IDL.Nat,
  'roomId' : IDL.Opt(IDL.Text),
  'dateTime' : IDL.Int,
  'prizePool' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'freeFireUID' : IDL.Text,
  'referralCode' : IDL.Text,
  'username' : IDL.Text,
  'totalWins' : IDL.Nat,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(IDL.Text),
  'isBanned' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'walletBalance' : IDL.Nat,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'transactionType' : TransactionType,
  'description' : IDL.Text,
  'timestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const DashboardStats = IDL.Record({
  'completedTournamentsCount' : IDL.Nat,
  'activeTournamentsCount' : IDL.Nat,
  'recentTransactions' : IDL.Vec(Transaction),
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'totalCommissionEarned' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'result' : IDL.Null,
  'matchReminder' : IDL.Null,
  'walletUpdate' : IDL.Null,
});
export const Notification = IDL.Record({
  'notificationType' : NotificationType,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Result = IDL.Record({
  'userId' : IDL.Principal,
  'totalPoints' : IDL.Nat,
  'position' : IDL.Nat,
  'tournamentId' : IDL.Nat,
  'kills' : IDL.Nat,
});
export const RevenueReport = IDL.Record({
  'totalCommissionProfit' : IDL.Nat,
  'totalPrizesDistributed' : IDL.Nat,
  'totalEntryFeesCollected' : IDL.Nat,
});
export const RoomCredentials = IDL.Record({
  'roomPassword' : IDL.Text,
  'roomId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFunds' : IDL.Func([IDL.Nat], [], []),
  'adjustWallet' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([IDL.Principal], [], []),
  'createTournament' : IDL.Func(
      [IDL.Text, MatchType, IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deleteTournament' : IDL.Func([IDL.Nat], [], []),
  'editTournament' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        MatchType,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'getAllTournaments' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, Tournament))],
      ['query'],
    ),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getResults' : IDL.Func([IDL.Nat], [IDL.Vec(Result)], ['query']),
  'getRevenueReport' : IDL.Func([], [RevenueReport], ['query']),
  'getRoomCredentials' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RoomCredentials)],
      ['query'],
    ),
  'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
  'getTournamentParticipants' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinTournament' : IDL.Func([IDL.Nat], [], []),
  'leaveTournament' : IDL.Func([IDL.Nat], [], []),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'register' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unbanUser' : IDL.Func([IDL.Principal], [], []),
  'uploadResults' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Nat))],
      [],
      [],
    ),
  'uploadRoomCredentials' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchType = IDL.Variant({
    'duo' : IDL.Null,
    'solo' : IDL.Null,
    'squad' : IDL.Null,
  });
  const TournamentStatus = IDL.Variant({
    'active' : IDL.Null,
    'upcoming' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Tournament = IDL.Record({
    'matchType' : MatchType,
    'status' : TournamentStatus,
    'title' : IDL.Text,
    'participants' : IDL.Vec(IDL.Principal),
    'mapType' : IDL.Text,
    'roomPassword' : IDL.Opt(IDL.Text),
    'totalSlots' : IDL.Nat,
    'entryFee' : IDL.Nat,
    'currentSlots' : IDL.Nat,
    'roomId' : IDL.Opt(IDL.Text),
    'dateTime' : IDL.Int,
    'prizePool' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'freeFireUID' : IDL.Text,
    'referralCode' : IDL.Text,
    'username' : IDL.Text,
    'totalWins' : IDL.Nat,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(IDL.Text),
    'isBanned' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'walletBalance' : IDL.Nat,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'transactionType' : TransactionType,
    'description' : IDL.Text,
    'timestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const DashboardStats = IDL.Record({
    'completedTournamentsCount' : IDL.Nat,
    'activeTournamentsCount' : IDL.Nat,
    'recentTransactions' : IDL.Vec(Transaction),
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'totalCommissionEarned' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'result' : IDL.Null,
    'matchReminder' : IDL.Null,
    'walletUpdate' : IDL.Null,
  });
  const Notification = IDL.Record({
    'notificationType' : NotificationType,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Result = IDL.Record({
    'userId' : IDL.Principal,
    'totalPoints' : IDL.Nat,
    'position' : IDL.Nat,
    'tournamentId' : IDL.Nat,
    'kills' : IDL.Nat,
  });
  const RevenueReport = IDL.Record({
    'totalCommissionProfit' : IDL.Nat,
    'totalPrizesDistributed' : IDL.Nat,
    'totalEntryFeesCollected' : IDL.Nat,
  });
  const RoomCredentials = IDL.Record({
    'roomPassword' : IDL.Text,
    'roomId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFunds' : IDL.Func([IDL.Nat], [], []),
    'adjustWallet' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([IDL.Principal], [], []),
    'createTournament' : IDL.Func(
        [IDL.Text, MatchType, IDL.Nat, IDL.Nat, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deleteTournament' : IDL.Func([IDL.Nat], [], []),
    'editTournament' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          MatchType,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'getAllTournaments' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, Tournament))],
        ['query'],
      ),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getResults' : IDL.Func([IDL.Nat], [IDL.Vec(Result)], ['query']),
    'getRevenueReport' : IDL.Func([], [RevenueReport], ['query']),
    'getRoomCredentials' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RoomCredentials)],
        ['query'],
      ),
    'getTournament' : IDL.Func([IDL.Nat], [IDL.Opt(Tournament)], ['query']),
    'getTournamentParticipants' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinTournament' : IDL.Func([IDL.Nat], [], []),
    'leaveTournament' : IDL.Func([IDL.Nat], [], []),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'register' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unbanUser' : IDL.Func([IDL.Principal], [], []),
    'uploadResults' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Nat))],
        [],
        [],
      ),
    'uploadRoomCredentials' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };