/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Transaction {
    transactionType: TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
}
export interface RevenueReport {
    totalCommissionProfit: bigint;
    totalPrizesDistributed: bigint;
    totalEntryFeesCollected: bigint;
}
export interface Result {
    userId: Principal;
    totalPoints: bigint;
    position: bigint;
    tournamentId: bigint;
    kills: bigint;
}
export interface Notification {
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}
export interface Tournament {
    matchType: MatchType;
    status: TournamentStatus;
    title: string;
    participants: Array<Principal>;
    mapType: string;
    roomPassword?: string;
    totalSlots: bigint;
    entryFee: bigint;
    currentSlots: bigint;
    roomId?: string;
    dateTime: bigint;
    prizePool: bigint;
}
export interface RoomCredentials {
    roomPassword: string;
    roomId: string;
}
export interface DashboardStats {
    completedTournamentsCount: bigint;
    activeTournamentsCount: bigint;
    recentTransactions: Array<Transaction>;
    totalUsers: bigint;
    totalRevenue: bigint;
    totalCommissionEarned: bigint;
}
export interface UserProfile {
    freeFireUID: string;
    referralCode: string;
    username: string;
    totalWins: bigint;
    email: string;
    referredBy?: string;
    isBanned: boolean;
    phoneNumber: string;
    walletBalance: bigint;
}
export enum MatchType {
    duo = "duo",
    solo = "solo",
    squad = "squad"
}
export enum NotificationType {
    result = "result",
    matchReminder = "matchReminder",
    walletUpdate = "walletUpdate"
}
export enum TournamentStatus {
    active = "active",
    upcoming = "upcoming",
    cancelled = "cancelled",
    completed = "completed"
}
export enum TransactionType {
    credit = "credit",
    debit = "debit"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFunds(amount: bigint): Promise<void>;
    adjustWallet(userId: Principal, amount: bigint, isCredit: boolean, reason: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(userId: Principal): Promise<void>;
    createTournament(title: string, matchType: MatchType, entryFee: bigint, prizePool: bigint, mapType: string, dateTime: bigint, totalSlots: bigint): Promise<bigint>;
    deleteTournament(tournamentId: bigint): Promise<void>;
    editTournament(tournamentId: bigint, title: string, matchType: MatchType, entryFee: bigint, prizePool: bigint, mapType: string, dateTime: bigint, totalSlots: bigint): Promise<void>;
    getAllTournaments(): Promise<Array<[bigint, Tournament]>>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<DashboardStats>;
    getNotifications(): Promise<Array<Notification>>;
    getResults(tournamentId: bigint): Promise<Array<Result>>;
    getRevenueReport(): Promise<RevenueReport>;
    getRoomCredentials(tournamentId: bigint): Promise<RoomCredentials | null>;
    getTournament(tournamentId: bigint): Promise<Tournament | null>;
    getTournamentParticipants(tournamentId: bigint): Promise<Array<Principal>>;
    getTransactionHistory(): Promise<Array<Transaction>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    joinTournament(tournamentId: bigint): Promise<void>;
    leaveTournament(tournamentId: bigint): Promise<void>;
    markNotificationAsRead(index: bigint): Promise<void>;
    register(username: string, email: string, freeFireUID: string, phoneNumber: string, referredByCode: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    unbanUser(userId: Principal): Promise<void>;
    uploadResults(tournamentId: bigint, resultsList: Array<[Principal, bigint, bigint]>): Promise<void>;
    uploadRoomCredentials(tournamentId: bigint, roomId: string, roomPassword: string): Promise<void>;
}
import type { DashboardStats as _DashboardStats, MatchType as _MatchType, Notification as _Notification, NotificationType as _NotificationType, RoomCredentials as _RoomCredentials, Tournament as _Tournament, TournamentStatus as _TournamentStatus, Transaction as _Transaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFunds(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFunds(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFunds(arg0);
            return result;
        }
    }
    async adjustWallet(arg0: Principal, arg1: bigint, arg2: boolean, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adjustWallet(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adjustWallet(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0);
            return result;
        }
    }
    async createTournament(arg0: string, arg1: MatchType, arg2: bigint, arg3: bigint, arg4: string, arg5: bigint, arg6: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTournament(arg0, to_candid_MatchType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTournament(arg0, to_candid_MatchType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async deleteTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTournament(arg0);
            return result;
        }
    }
    async editTournament(arg0: bigint, arg1: string, arg2: MatchType, arg3: bigint, arg4: bigint, arg5: string, arg6: bigint, arg7: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editTournament(arg0, arg1, to_candid_MatchType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editTournament(arg0, arg1, to_candid_MatchType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async getAllTournaments(): Promise<Array<[bigint, Tournament]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTournaments();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTournaments();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResults(arg0: bigint): Promise<Array<Result>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResults(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResults(arg0);
            return result;
        }
    }
    async getRevenueReport(): Promise<RevenueReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueReport();
            return result;
        }
    }
    async getRoomCredentials(arg0: bigint): Promise<RoomCredentials | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoomCredentials(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoomCredentials(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournament(arg0: bigint): Promise<Tournament | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournament(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournament(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentParticipants(arg0: bigint): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentParticipants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentParticipants(arg0);
            return result;
        }
    }
    async getTransactionHistory(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async joinTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.joinTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinTournament(arg0);
            return result;
        }
    }
    async leaveTournament(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveTournament(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveTournament(arg0);
            return result;
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1, arg2, arg3, to_candid_opt_n35(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async unbanUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0);
            return result;
        }
    }
    async uploadResults(arg0: bigint, arg1: Array<[Principal, bigint, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadResults(arg0, arg1);
            return result;
        }
    }
    async uploadRoomCredentials(arg0: bigint, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadRoomCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadRoomCredentials(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DashboardStats_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_MatchType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchType): MatchType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TournamentStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TournamentStatus): TournamentStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Tournament_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tournament): Tournament {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Transaction_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoomCredentials]): RoomCredentials | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tournament]): Tournament | null {
    return value.length === 0 ? null : from_candid_Tournament_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeFireUID: string;
    referralCode: string;
    username: string;
    totalWins: bigint;
    email: string;
    referredBy: [] | [string];
    isBanned: boolean;
    phoneNumber: string;
    walletBalance: bigint;
}): {
    freeFireUID: string;
    referralCode: string;
    username: string;
    totalWins: bigint;
    email: string;
    referredBy?: string;
    isBanned: boolean;
    phoneNumber: string;
    walletBalance: bigint;
} {
    return {
        freeFireUID: value.freeFireUID,
        referralCode: value.referralCode,
        username: value.username,
        totalWins: value.totalWins,
        email: value.email,
        referredBy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.referredBy)),
        isBanned: value.isBanned,
        phoneNumber: value.phoneNumber,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedTournamentsCount: bigint;
    activeTournamentsCount: bigint;
    recentTransactions: Array<_Transaction>;
    totalUsers: bigint;
    totalRevenue: bigint;
    totalCommissionEarned: bigint;
}): {
    completedTournamentsCount: bigint;
    activeTournamentsCount: bigint;
    recentTransactions: Array<Transaction>;
    totalUsers: bigint;
    totalRevenue: bigint;
    totalCommissionEarned: bigint;
} {
    return {
        completedTournamentsCount: value.completedTournamentsCount,
        activeTournamentsCount: value.activeTournamentsCount,
        recentTransactions: from_candid_vec_n23(_uploadFile, _downloadFile, value.recentTransactions),
        totalUsers: value.totalUsers,
        totalRevenue: value.totalRevenue,
        totalCommissionEarned: value.totalCommissionEarned
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transactionType: _TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
}): {
    transactionType: TransactionType;
    description: string;
    timestamp: bigint;
    amount: bigint;
} {
    return {
        transactionType: from_candid_TransactionType_n26(_uploadFile, _downloadFile, value.transactionType),
        description: value.description,
        timestamp: value.timestamp,
        amount: value.amount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notificationType: _NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
}): {
    notificationType: NotificationType;
    isRead: boolean;
    message: string;
    timestamp: bigint;
} {
    return {
        notificationType: from_candid_NotificationType_n31(_uploadFile, _downloadFile, value.notificationType),
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    matchType: _MatchType;
    status: _TournamentStatus;
    title: string;
    participants: Array<Principal>;
    mapType: string;
    roomPassword: [] | [string];
    totalSlots: bigint;
    entryFee: bigint;
    currentSlots: bigint;
    roomId: [] | [string];
    dateTime: bigint;
    prizePool: bigint;
}): {
    matchType: MatchType;
    status: TournamentStatus;
    title: string;
    participants: Array<Principal>;
    mapType: string;
    roomPassword?: string;
    totalSlots: bigint;
    entryFee: bigint;
    currentSlots: bigint;
    roomId?: string;
    dateTime: bigint;
    prizePool: bigint;
} {
    return {
        matchType: from_candid_MatchType_n9(_uploadFile, _downloadFile, value.matchType),
        status: from_candid_TournamentStatus_n11(_uploadFile, _downloadFile, value.status),
        title: value.title,
        participants: value.participants,
        mapType: value.mapType,
        roomPassword: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.roomPassword)),
        totalSlots: value.totalSlots,
        entryFee: value.entryFee,
        currentSlots: value.currentSlots,
        roomId: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.roomId)),
        dateTime: value.dateTime,
        prizePool: value.prizePool
    };
}
function from_candid_tuple_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _Tournament]): [bigint, Tournament] {
    return [
        value[0],
        from_candid_Tournament_n7(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duo: null;
} | {
    solo: null;
} | {
    squad: null;
}): MatchType {
    return "duo" in value ? MatchType.duo : "solo" in value ? MatchType.solo : "squad" in value ? MatchType.squad : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    upcoming: null;
} | {
    cancelled: null;
} | {
    completed: null;
}): TournamentStatus {
    return "active" in value ? TournamentStatus.active : "upcoming" in value ? TournamentStatus.upcoming : "cancelled" in value ? TournamentStatus.cancelled : "completed" in value ? TournamentStatus.completed : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    credit: null;
} | {
    debit: null;
}): TransactionType {
    return "credit" in value ? TransactionType.credit : "debit" in value ? TransactionType.debit : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: null;
} | {
    matchReminder: null;
} | {
    walletUpdate: null;
}): NotificationType {
    return "result" in value ? NotificationType.result : "matchReminder" in value ? NotificationType.matchReminder : "walletUpdate" in value ? NotificationType.walletUpdate : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _Tournament]>): Array<[bigint, Tournament]> {
    return value.map((x)=>from_candid_tuple_n6(_uploadFile, _downloadFile, x));
}
function to_candid_MatchType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchType): _MatchType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    freeFireUID: string;
    referralCode: string;
    username: string;
    totalWins: bigint;
    email: string;
    referredBy?: string;
    isBanned: boolean;
    phoneNumber: string;
    walletBalance: bigint;
}): {
    freeFireUID: string;
    referralCode: string;
    username: string;
    totalWins: bigint;
    email: string;
    referredBy: [] | [string];
    isBanned: boolean;
    phoneNumber: string;
    walletBalance: bigint;
} {
    return {
        freeFireUID: value.freeFireUID,
        referralCode: value.referralCode,
        username: value.username,
        totalWins: value.totalWins,
        email: value.email,
        referredBy: value.referredBy ? candid_some(value.referredBy) : candid_none(),
        isBanned: value.isBanned,
        phoneNumber: value.phoneNumber,
        walletBalance: value.walletBalance
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchType): {
    duo: null;
} | {
    solo: null;
} | {
    squad: null;
} {
    return value == MatchType.duo ? {
        duo: null
    } : value == MatchType.solo ? {
        solo: null
    } : value == MatchType.squad ? {
        squad: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
